name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    container: customcommander/webdev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Build
        run: yarn run build
      - name: Release
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn semantic-release --no-ci
