name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    container:
      image: customcommander/webdev
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn
      - name: Build
        run: make build
        shell: bash {0}
      - name: Release
        run: yarn semantic-release --no-ci
